### ISSUE TITLE
Sharing a sample submission file

### ISSUE THREAD

**Issue by mohammed-elkomy** [RanaMalhas/QRCD#2]
SA Dr Rana,

May you please share a sample submission file to make sure our systems are generating the expected format?

I tried to trace the expected structure but it seems there's something wrong with "adjust_start" and  "adjust_end" functions,

Steps to replicate:
`          
org_word_start_position = 20
org_word_end_position = 20
org_paragraph_text = "إن مجرمين في عذاب جهنم خالدون . لا يفتر عنهم هم فيه مبلسون . ما ظلمناهم لكن كانوا هم ظالمين . نادوا يا مالك يقض علينا ربك قال إنكم ماكثون . لقد جئناكم حق لكن أكثركم حق كارهون . أم أبرموا أمرا إنا مبرمون . أم يحسبون أنا لا نسمع سرهم نجواهم بلى رسلنا لديهم يكتبون ."

adj_word_start_position = adjust_start(org_paragraph_text, org_word_start_position)
adj_word_end_position = adjust_end(org_paragraph_text, org_word_end_position)
`
adj_word_start_position will be 17 and adj_word_end_position will be 16 which will cause an error with range operations in the evaluation function. (I think we must assert adj_word_start_position<=adj_word_end_position)

Thanks

**Comment by RanaMalhas** [comment]
Wa-Alykum Al-Salam Mohammad,

Thank you for your email.

Please find attached a sample prediction file. I have also uploaded a re-factored and cleaned version of the eval script, which may need further cleaning/refactoring.

The error is caused by the preprocessing that the run_squad.py of the original BBERT does on punctuation; it embraces each punctuation with at least one space.

I will soon upload the preprocessing script  to apply on the training and test datasets.

B. Regard,

Rana Malhas


From: Mohammed Alaa El komy ***@***.***>
Sent: Monday, September 12, 2022 6:24 PM
To: RanaMalhas/QRCD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ALERT: Non-QU Sender] [RanaMalhas/QRCD] Sharing a sample submission file (Issue #2)


SA Dr Rana,

May you please share a sample submission file to make sure our systems are generating the expected format?

I tried to trace the expected structure but it seems there's something wrong with "adjust_start" and "adjust_end" functions,

Steps to replicate:
`
org_word_start_position = 20
org_word_end_position = 20
org_paragraph_text = "إن مجرمين في عذاب جهنم خالدون . لا يفتر عنهم هم فيه مبلسون . ما ظلمناهم لكن كانوا هم ظالمين . نادوا يا مالك يقض علينا ربك قال إنكم ماكثون . لقد جئناكم حق لكن أكثركم حق كارهون . أم أبرموا أمرا إنا مبرمون . أم يحسبون أنا لا نسمع سرهم نجواهم بلى رسلنا لديهم يكتبون ."

adj_word_start_position = adjust_start(org_paragraph_text, org_word_start_position)
adj_word_end_position = adjust_end(org_paragraph_text, org_word_end_position)
`
adj_word_start_position will be 17 and adj_word_end_position will be 16 which will cause an error with range operations in the evaluation function.

Thanks

**Comment by RanaMalhas** [comment]
AA Mohammad,

I have uploaded the qrcd_preprocessing.py script and provided some instructions elaborating on the need to preprocess the test dataset before running the evaluation script.

Please note that the script expects the input data file to be in SQuAD format. You would need to execute this script on the train and test datasets.

Should you have any other concerns/issues, please let me know.

Thank you


From: Mohammed Alaa El komy ***@***.***>
Sent: Monday, September 12, 2022 6:24 PM
To: RanaMalhas/QRCD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ALERT: Non-QU Sender] [RanaMalhas/QRCD] Sharing a sample submission file (Issue #2)


SA Dr Rana,

May you please share a sample submission file to make sure our systems are generating the expected format?

I tried to trace the expected structure but it seems there's something wrong with "adjust_start" and "adjust_end" functions,

Steps to replicate:
`
org_word_start_position = 20
org_word_end_position = 20
org_paragraph_text = "إن مجرمين في عذاب جهنم خالدون . لا يفتر عنهم هم فيه مبلسون . ما ظلمناهم لكن كانوا هم ظالمين . نادوا يا مالك يقض علينا ربك قال إنكم ماكثون . لقد جئناكم حق لكن أكثركم حق كارهون . أم أبرموا أمرا إنا مبرمون . أم يحسبون أنا لا نسمع سرهم نجواهم بلى رسلنا لديهم يكتبون ."

adj_word_start_position = adjust_start(org_paragraph_text, org_word_start_position)
adj_word_end_position = adjust_end(org_paragraph_text, org_word_end_position)
`
adj_word_start_position will be 17 and adj_word_end_position will be 16 which will cause an error with range operations in the evaluation function.

Thanks

**Comment by mohammed-elkomy** [comment]
Thanks so much
